name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: Lint
        run: yarn lint -- --quiet

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Unit tests
        run: yarn test
        env:
          NODE_ENV: test
